### ISSUE TITLE
Suggested issues from the `goodpractice` package

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/kmeans_R#33]
I ran `goodpractice::gp()` to identify likely sources of errors and style issues. I paste the output below as a png (only way I could easily share with you). I suggest downloading the [`goodpractice`](https://github.com/MangoTheCat/goodpractice) package and running it yourself to address these issues:

![screen shot 2018-03-15 at 2 25 54 pm](https://user-images.githubusercontent.com/6865016/37492076-2719263e-285d-11e8-8bee-c87843d12ed9.png)
![screen shot 2018-03-15 at 2 28 25 pm](https://user-images.githubusercontent.com/6865016/37492080-2afc95ba-285d-11e8-8861-a1e62bece758.png)

**Comment by bradleypick** [comment]
Attempts were made to address some of the issues raised by `goodpractice::gp()` in the commits above. Closing for now because I want another green badge on the README.
